GopStop/urls.py
from django.conf.urls import include, url, handler403, handler404, handler500
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = "GopStop page administrateur"
admin.site.index_title = "Bienvenue sur la partie admin de GopStop"

urlpatterns = [
    url(r'^', include('forum.urls', namespace="forum")),
    url(r'^admin/', admin.site.urls)
] 

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = 'gopstop.error.error_403'
handler404 = 'gopstop.error.error_404'
handler500 = 'gopstop.error.error_500'

forum/urls.py
from django.conf.urls import url
from django.urls import path
from django.conf import settings
from forum.views import home as home, post, account, comment, vote, user

app_name = "forum"
urlpatterns = [
    path('', home.home, name='default'),
    path('home', home.home, name='home'),
    path('home/cat_sort/<int:cat_id>', home.home, name='cat-sort'),
    path('login', account.login, name='login'),
    path('logout', account.logout, name='logout'),
    path('register', account.register, name='register'),
    path('reset_password', account.reset_password, name='reset-password'),
    path('new_post', post.new_post, name='new-post'),
    path('post/detail/<int:id>', post.post_detail, name='post-detail'),
    path('post/detail/<int:post_id>/new_comment', comment.new_comment, name='new-comment'),
    path('post/detail/<int:post_id>/comment_delete/<int:comment_id>', comment.comment_delete, name='comment-delete'),
    path('post/detail/<int:post_id>/comment_update/<int:comment_id>', comment.comment_update, name='comment-update'),
    path('post/delete/<int:id>', post.post_delete, name='post-delete'),
    path('post/update/<int:id>', post.post_update, name='post-update'),
    path('search', post.post_search, name='post-search'),
    path('post/detail/<int:id>/like', vote.post_like, name='post-like'),
    path('post/detail/<int:id>/dislike', vote.post_dislike, name='post-dislike'),
    path('user/posts', user.user_posts, name='user-posts'),
    path('user/history', user.user_history, name='user-history'),
    path('user/profile', user.user_profile, name='user-profile'),
    path('user/profile/update/information', user.user_update_information, name='user-update-information'),
    path('user/profile/update/password', user.user_update_password, name='user-update-password'),
    path('user/profile/delete', user.user_profile_delete, name='user-profile-delete'),
    path('user/profile/add_profile_picture', user.user_add_profile_picture, name='user-add-profile-picture'),
]

forum/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    first_name = forms.CharField(max_length=150)
    last_name = forms.CharField(max_length=150)
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name','email','password1','password2']

forum/views/account.py
from django.shortcuts import render, redirect
from django.utils import timezone
from forum.models import *
from forum.utils.account import is_connected
from django.contrib.auth import forms, authenticate as django_auth, login as django_log, logout as django_logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.urls import reverse
from forum.forms import UserRegisterForm
import urllib
import hashlib
import datetime



def register(request):
    """
    Handle the connection of the login page.
    """
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, 'Compte créer pour ' + username + '!')
            return redirect('forum:home')
    else:
        form = UserRegisterForm()
    return render(request, "forum/register.html", {'form':form} )

def login(request):
    if request.POST:
        username = request.POST['username']
        password = request.POST['password']
        user = django_auth(request, username=username, password=password)
        if user is not None:
            django_log(request, user)
            return redirect('forum:home')
        else:
            messages.warning(request, "Nom d'utilisateur ou mot de passe incorrecte.")
            return redirect('forum:login')
    return render(request, 'forum/login.html')

@login_required
def logout(request):
    django_logout(request)
    return redirect('forum:home')

def reset_password(request):
    return render(request, 'forum/reset_password.html')

forum/views/comment.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, Http404
from django.views.decorators.csrf import csrf_exempt
from django.utils import timezone
from forum.models import Post, SpecialUser, Category, Comment
from datetime import timedelta, datetime
from django.utils.text import slugify
from django.contrib import messages
import json
from django.contrib.auth import authenticate

def new_comment(request, post_id):
    if request.user.is_authenticated:
        if request.POST:
            comment = Comment.objects.create(
                post = get_object_or_404(Post, id = post_id), 
                description = request.POST["description"], 
                user = request.user,
                )
            comment.save()
    return redirect('forum:post-detail', id = post_id)

def comment_delete(request, post_id, comment_id):
    try:
        user_comment = get_object_or_404(Comment, id = comment_id)
        #Si l'utilisateur connecté est l'utilisateur qui à créer le commentare ou il fait parti du staff
        if request.user.is_authenticated and request.user == user_comment.user or request.user.is_staff: 
            #alors il peut supprimer le commentaire
            Comment.objects.filter(id=comment_id).delete()
            messages.success(request, 'Le commentaire à bien été supprimé')
        else:
            messages.warning(request, "Vous ne pouvez pas supprimer ce commentaire car vous n'êtes pas l'auteur")            
        return redirect('forum:post-detail', id = post_id)
    except Exception as e:
        raise e

def comment_update(request, post_id, comment_id):
    try:
        user_comment = get_object_or_404(Comment, id = comment_id)
        if request.user.is_authenticated and request.user == user_comment.user:
            Comment.objects.filter(id = comment_id).update(description = request.POST["description"])
            messages.success(request, 'Le commentaire à bien été modifié')
            return redirect('forum:post-detail', id = post_id)
    except Exception as e:
        raise e

forum/views/home.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.utils import timezone
from datetime import timedelta, datetime
from forum.models import Post, SpecialUser, Category, Comment
from forum.utils.user import get_cleaned_posts
from django.utils.text import slugify
import json
from django.contrib.auth import authenticate


def home(request, cat_id = None):
    user_is_connected = False
    #Recupére l'objet Category a partir de son id passé en parametre s'il est défini, sinon la valeur est nulle
    categ = get_object_or_404(Category, id= cat_id) if cat_id is not None else None
    #Récupère la liste des postes qui ont pour catégorie "categ" si le parametre cat_id est specifié, sinon on récupère tous les posts
    posts = Post.objects.all() if cat_id is None else Post.objects.filter(category = categ)

    if request.user.is_authenticated:
        user_is_connected = True
    post_content = get_cleaned_posts(posts)


    
    cat_content = []
    for category in Category.objects.all():
        cat_content.append({
            'category' : category,
            'count' : Post.objects.filter(category = category).count(),
        })

    context = {
        'user_is_connected' : user_is_connected,
        'post_content': post_content,   
        'cat_content' : cat_content,
        #Retourne la catégorie passée en parametre dans le request pour pouvoir afficher son nom dans le message du template "Il n'y a aucun post pour la catégorie pour le moment"
        'categ' : categ,
    }
    return render(request, 'forum/home.html', context= context)

forum/views/post.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, Http404
from django.views.decorators.csrf import csrf_exempt
from django.utils import timezone
from forum.models import Post, SpecialUser, Category, Comment
from forum.utils.user import get_cleaned_posts
from datetime import timedelta, datetime
from django.contrib import messages
from django.utils.text import slugify
from django.contrib.auth import authenticate
import json

def new_post(request):
    user_is_connected = True if request.user.is_authenticated else False
    if request.user.is_authenticated:
        if request.POST:
            post = Post.objects.create(
                user = request.user,
                description = request.POST["description"], 
                title = request.POST["title"], 
                model_pic = request.FILES["model_pic"],
                category = Category.objects.get(id = request.POST['category'])
                )
            post.save()
            return redirect('forum:post-detail', id = post.id)
        else:
            categories = Category.objects.all()
            user_is_connected = True
            context = {
                'user_is_connected' : user_is_connected,
                'categories' : categories
            }
            return render(request, 'forum/new_post.html', context= context) 
    return redirect('forum:home')

def post_detail(request, id):
    try: 
        user_is_connected = True if request.user.is_authenticated else False
        post = get_object_or_404(Post, id = id)
        like_number = post.likes.count()
        dislike_number = post.dislikes.count()
        post_user = post.user
        post_user_profile_pic = None
        if post_user.specialuser.user_profile_pic is not None:
            post_user_profile_pic = post_user.specialuser.user_profile_pic.model_pic
        comments = Comment.objects.filter(post = post)
        context = {
            'post': post,
            'comments' : comments,
            'user_is_connected' : user_is_connected,
            'like_number' : like_number,
            'dislike_number': dislike_number,
            'post_user_profile_pic' : post_user_profile_pic,
        }
        return render(request, 'forum/post_detail.html', context= context) 
    except Exception as e: 
        raise e

def post_delete(request, id):
    try:
        post = get_object_or_404(Post, id=id)
        if request.user.is_authenticated and post.user == request.user or request.user.is_staff:
            messages.success(request, 'Le post intitulé "' + post.title + '" à bien été supprimé')
            post.delete()
        else:
            messages.warning(request, "vous ne pouvez pas supprimer le poste intitulé '" + post.title + "' car vous n'êtes pas l'auteur") 
        return redirect('forum:home')
    except Exception as e:
        raise e

def post_update(request, id):
    user_is_connected = True if request.user.is_authenticated else False
    #get_object_or_404 retourn un objet, donc les propriétés sont accessible
    user_post = get_object_or_404(Post, id=id)
    if request.user.is_authenticated and user_post.user == request.user or request.user.is_staff:
        #posts.objects.filter() retourne une collection d'objet, les propriétés ne sont pas accessibles
        post = Post.objects.filter(id=id)
        if request.POST:
            post.update(
                user = request.user,
                description = request.POST["description"], 
                title = request.POST["title"], 
                category = Category.objects.get(id = request.POST['category'])
                )
            messages.success(request, 'Le post à bien été modifié')
            return redirect('forum:post-detail', id = id)
        else:
            categories = Category.objects.all()
            post = Post.objects.get(id = id)
            context = {
                'user_is_connected' : user_is_connected,
                'post' : post,
                'categories' : categories,
            }
            return render(request, 'forum/post_update.html', context= context) 
    else:
        messages.warning(request, "vous ne pouvez pas modifier le poste intitulé '" + post.title + "' car vous n'êtes pas l'auteur") 
    return redirect('forum:home')

def post_search(request):
    user_is_connected = True if request.user.is_authenticated else False
    if request.POST:
        posts = Post.objects.filter(title__icontains= request.POST["recherche"])
        post_content = get_cleaned_posts(posts)
        context = {
            'user_is_connected' : user_is_connected,
            'post_content': post_content,   
        }
        if posts.count() == 0:
            messages.warning(request, "Aucun résultat pour la recherche '" + request.POST["recherche"] + "'.")
            return redirect('forum:home')
        else:
            messages.info(request, "Résultat(s) pour la recherche '" + request.POST["recherche"] +  "'.")
            return render(request, 'forum/search_result.html', context = context)
    return redirect('forum:home')

forum/views/vote.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, Http404
from django.views.decorators.csrf import csrf_exempt
from django.utils import timezone
from forum.models import Post, SpecialUser, Category, Comment
from datetime import timedelta, datetime
from django.utils.text import slugify
from django.contrib import messages
import json
from django.contrib.auth import authenticate


def post_like(request, id):
    try:
        post = get_object_or_404(Post, id=id)
        if request.user.is_anonymous:
            messages.error(request, 'Vous devez vous connecter pour pouvoir liker un post')
            return redirect('forum:post-detail', id = id)
        #Si l'utilisateur n'as pas déjà liké le post et n'as pas disliké le post
        elif request.user not in post.likes.all() and request.user not in post.dislikes.all():
            #Ajout d'un simple like au post
            post.likes.add(request.user)
            messages.success(request, 'Vous avez bien liké ce post')
            return redirect('forum:post-detail', id = id)
        #Si l'utilisateur n'as pas déjà liké le post et par contre a déjà disliké le post
        elif request.user not in post.likes.all() and request.user in post.dislikes.all():
            #Le dislike de l'utilisateur sur le post est supprimé
            post.dislikes.remove(request.user)
            #Un like est ajouté
            post.likes.add(request.user)
            messages.info(request, "Votre dislike à bien été changé en like")
            return redirect('forum:post-detail', id = id)
        else:
            messages.info(request, 'Votre like à bien été retiré')
            post.likes.remove(request.user)
            return redirect('forum:post-detail', id = id)
    except Exception as e:
        raise e


def post_dislike(request, id):
    try:
        post = get_object_or_404(Post, id=id)
        if request.user.is_anonymous:
            messages.error(request, 'Vous devez vous connecter pour pouvoir disliker un post')
            return redirect('forum:post-detail', id = id)
        elif request.user not in post.dislikes.all() and request.user not in post.likes.all():
            post.dislikes.add(request.user)
            messages.success(request, 'Vous avez bien disliké ce post')
            return redirect('forum:post-detail', id = id)
        elif request.user not in post.dislikes.all() and request.user in post.likes.all():
            post.likes.remove(request.user)
            post.dislikes.add(request.user)
            messages.info(request, "Votre like à bien été changé en dislike")
            return redirect('forum:post-detail', id = id)
        else:
            messages.info(request, 'Votre dislike à bien été retiré')
            post.dislikes.remove(request.user)
            return redirect('forum:post-detail', id = id)
    except Exception as e:
        raise e

forum/templates/forum/change_password.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="">
    <title>GopStop | Forum</title>

    <!-- Bootstrap core CSS -->

    <link type="text/css" href="{% static 'css/bootstrap.min.css' %}?v=0.0.1" rel="stylesheet">

    <link type="text/css" href="{% static 'fonts/css/font-awesome.min.css' %}?v=0.0.1" rel="stylesheet">
    <link type="text/css" href="{% static 'css/animate.min.css' %}?v=0.0.1" rel="stylesheet">



    <style type="text/css">
        video#bgvid {
            position: fixed;
            top: 50%;
            left: 50%;
            min-width: 100%;
            min-height: 100%;
            width: auto;
            height: auto;
            z-index: -100;
            transform: translateX(-50%) translateY(-50%);
            background-size: cover;
            transition: 1s opacity;
        }
    </style>
</head>

<body style="background:#F7F7F7;">
        <div>
            <a class="hiddenanchor" id="toregister"></a>
            <a class="hiddenanchor" id="tologin"></a>

            <div id="wrapper">
                <div id="login" class="animate form">
                    <section class="login_content">
                        {% if not send %}
                            <form method="post">
                                <h2 style="color: white">Changer votre mot de passe</h2>
                                {% csrf_token %}
                                {% for field in form %}
                                <div>
                                    {{ field }}
                                </div>
                                {% endfor %}
                                <input type="submit" class="btn btn-default submit" value="Enregistrer">
                                <div class="clearfix"></div>
                                <div class="separator"></div>
                            </form>
                            <!-- form -->
                        {% else %}
                            <h2 style="color: white">{{content}}</h2>
                        {% endif %}
                    </section>
                    <!-- content -->
                </div>
            </div>
        </div>
    </body>
    </html>

forum/templates/forum/post_detail.html
{% extends "forum/base.html" %}
{% load auth_extras %}
{% load static %}
{% load staticfiles %}
{% block content %}
        
        <section class="content">
            <br>
            <br>
            <br>
            <section class="content"></div>
                <div class="container">
                    <div class="row">
                        <div class="col-lg-8 col-md-8">
                            <!-- POST -->
                            <div class="post beforepagination">
                            <div class="topwrap">
                                <div class="userinfo pull-left">
                                    
                                </div>
                            </div>
                            
                                <div class="posttext pull-left">
                                    <div class="avatar">
                                    <img src="/media/{{post_user_profile_pic}}" width="40" height="40">
                                    <p style="font-weight:bold;">{{post.user}}:</p>
                                    {% if request.user == post.user %}
                                    <div class="status green">
                                        &nbsp;
                                    </div>
                                    {% else %}
                                    <div class="status red">
                                        &nbsp;
                                    </div>
                                    {% endif %}
                                    
                                    </div>
                                    
                                    <img src="/media/{{ post.model_pic}}" alt="" width="200" height="200" />
                                    <h2>{{ post.title }}</h2>
                                    <p>
                                        {{ post.description }}
                                    </p>
                                    {% if request.user.id == post.user.id or request.user|has_group:"moderator" %}
                                    <form action="{% url 'forum:post-update' post.id %}" method="GET">
                                        {% csrf_token %}
                                        <input name="post_update" type="submit" class="btn" value="Modifier ce post">
                                    </form>
                                    <form onsubmit="return confirm('Voulez vous vraiment supprimer ce post ?');" action="{% url 'forum:post-delete' post.id %}" method="POST">
                                        {% csrf_token %}
                                        <input name="post_delete" type="submit" class="btn btn-danger" value="Supprimer ce post">
                                    </form>
                                    {% endif %}
                                </div>
                                
                                <div class="clearfix"></div>
                                
                            </div>
                            <div class="postinfobot">
                                <div class="likeblock pull-left">
                                    <a href="{% url 'forum:post-like' post.id %}" class="up"><i class="fa fa-thumbs-o-up"></i> {{like_number}}</a>
                                    <a href="{% url 'forum:post-dislike' post.id %}" class="down"><i class="fa fa-thumbs-o-down"></i> {{dislike_number}}</a>
                                </div>
                                <div class="prev pull-left">
                                    <a href="#"><i class="fa fa-reply"></i></a>
                                </div>
                                <div class="posted pull-left">
                                    <i class="fa fa-clock-o"></i>
                                    Posté le : {{post.dt_creation}}
                                    Catégorie : {{post.category}}
                                </div>
                                <div class="next pull-right">
                                    <a href="#"><i class="fa fa-share"></i></a>
                                    <a href="#"><i class="fa fa-flag"></i></a>
                                </div>
                                <div class="clearfix"></div>
                                
                            </div>
                        </div>
                        <!-- POST -->
                        <div class="paginationf">
                            <div class="pull-left">
                                <a href="#" class="prevnext"><i class="fa fa-angle-left"></i></a>
                            </div>

                            <div class="pull-left">
                                <a href="#" class="prevnext last"><i class="fa fa-angle-right"></i></a>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                        <!-- POST -->
                        {% for comment in comments %}
                        <div class="post">
                            <div class="topwrap">
                                <div class="userinfo pull-left">
                                    <div class="avatar">
                                        
                                    </div>
                                    
                                </div>
                                <div class="posttext pull-left">
                                    <p style="font-weight:bold;">{{comment.user}} :</p>
                                    <p>
                                        {{comment.description}}
                                    </p>
                                </div>
                                <div class="clearfix"></div>
                            </div>
                            <div class="postinfobot">
                                <!-- 
                                <div class="likeblock pull-left">
                                    <a href="#" class="up"><i class="fa fa-thumbs-o-up"></i>10</a>
                                    <a href="#" class="down"><i class="fa fa-thumbs-o-down"></i>1</a>
                                </div>
                                
                                <div class="prev pull-left">
                                    <a href="#"><i class="fa fa-reply"></i></a>
                                </div>
                                -->
                                <div class="posted pull-left">
                                    <i class="fa fa-clock-o"></i>
                                    Posté le : {{comment.dt_creation}} par {{comment.user}} 
                                </div>
                                <div class="prev pull-left">
                                {% if user.id == comment.user.id %}

                                <form  action="{% url 'forum:comment-update' post.id comment.id %}" method="POST">
                                    {% csrf_token %}
                                    <div id="myModal" class="modal fade" role="dialog">
                                    <div class="modal-dialog">
    
                                        <!-- Modal content-->
                                        <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                                            <h4 class="modal-title">Modifier ce commentaire</h4>
                                        </div>
                                        <div class="modal-body">
                                            <div class="form-group">
                                                <label for="message-text" class="col-form-label">Saisir un commentaire :</label>
                                                <textarea class="form-control" id="message-text" name="description" id="description" placeholder="{{comment.description}}">{{comment.description}}</textarea>
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <input name="comment_update" type="submit" class="btn btn-primary" value="Valider">
                                            <button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>
                                        </div>
                                        </div>
    
                                    </div>
                                    </div>
                                    
                                </form>
                                <input type="button" value="Modifier ce commentaire" class="btn btn" data-toggle="modal" data-target="#myModal">
                                <form onsubmit="return confirm('Voulez vous vraiment supprimer ce commentaire ?');" action="{% url 'forum:comment-delete' post.id comment.id %}" method="POST">
                                        {% csrf_token %}
                                        <input name="comment_delete" type="submit" class="btn btn-danger" value="Supprimer ce commentaire">
                                </form>
                                <!-- Modal -->
                                {% elif user.id == comment.user.id or request.user|has_group:"moderator" %} 
                                <form onsubmit="return confirm('Voulez vous vraiment supprimer ce commentaire ?');" action="{% url 'forum:comment-delete' post.id comment.id %}" method="POST">
                                    {% csrf_token %}
                                    <input name="comment_delete" type="submit" class="btn btn-danger" value="Supprimer ce commentaire">
                                </form>
                                {% else %}
                                {% endif %}
                                </div>
                                <div class="clearfix"></div>
                                
                            </div>
                            
                        </div>
                        {% endfor %}
                        {% if user_is_connected %}
                        <!-- POST -->
                        <div class="post">
                                <form  action="{% url 'forum:new-comment' post.id %}" class="form" method="post">
                                {% csrf_token %}
                                
                                <div class="topwrap">
                                    <div class="userinfo pull-left">
                                        <div class="avatar">
                                            
                                        </div>
                                        
                                    </div>
                                    <div class="posttext pull-left">
                                        <div class="textwraper">
                                            <div class="postreply">
                                                Ecrire un commentaire
                                            </div>
                                            <textarea name="description" id="description" placeholder="Ecrire votre commentaire ici"></textarea>
                                        </div>
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                                <div class="postinfobot">
                                
                                    
                                    <div class="pull-right postreply">
                                        <div class="pull-left">
                                            <button type="submit" class="btn btn-primary">Ajouter le commentaire</button>
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                            </form>
                        </div>
                        {% endif %}
                        <!-- POST -->
                    </div>
                </div>
            </div>
        </section>
    </section>
            
            
                 
{% endblock %}